### ISSUE TITLE
[Question] Reuse some of your code parts

### ISSUE THREAD

**Issue by dfch** [RamblingCookieMonster/Infoblox#1]
Hi @RamblingCookieMonster I had a look at your module and saw that you are publishing this under MIT license. As we also have a basic PoSH [module for Infoblox REST integration](https://github.com/dfch/biz.dfch.PS.Ipam.Infoblox.Api) I wanted to formally ask if we could re-use some of your code. The reason for re-using/re-formatting (instead of just plain using yours) is that we have some kind of different basic architecture/approach (logging, error handling) and therefore would prefer to port some of your Cmdlets to our module.
Thanks in advance for your reply! Regards, Ronald

**Comment by RamblingCookieMonster** [comment]
Hi Ronald!

Appreciate the heads up - you're more than welcome to use any code from here, hope it helps!

Warren
